// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonResult {
    /// 返回码,0 成功，非0异常
    #[prost(int32, tag = "1")]
    pub ret_code: i32,
    /// 返回码描述
    #[prost(string, tag = "2")]
    pub ret_msg: ::prost::alloc::string::String,
}
